name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: make

      - name: Test
        run: make test

  coverage:
    runs-on: ubuntu-latest
    steps:

      - name: Ls before checkout
        run: ls -la

      - uses: actions/checkout@v3
        with:
          submodules: true
          clean: false
          fetch-depth: 0

#      - name: Clone
#        uses: GuillaumeFalourd/clone-github-repo-action@v2
#        with:
#          owner: 'Goutte'
#          repository: 'gitime'

      - name: Ls
        run: ls -la

      - name: Clone
        run: git clone --recurse-submodules https://github.com/Goutte/gitime cloned

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Generate coverage report
        run: make coverage

      - name: Generate integration tests coverage report
        run: make coverage-acceptance

      - name: Upload unit tests coverage report
        uses: codecov/codecov-action@v3
        with:
#          token: 50ed170f-08b5-4484-97d8-37771615ae42
          file: ./coverage-unit.txt
          flags: unittests
#          name: codecov-umbrella

      - name: Upload integration tests coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage-integration.txt
          flags: integration
